version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-23-0
  reek:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
exclude_patterns:
- ./*.yml
- ./*.js
- ./*.json
- app/assets/**/*
- app/locales/**/*
- app/views/**/*
- bin/**/*
- config/**/*
- db/**/*
- doc/**/*
- lib/**/*
- public/**/*
- spec/**/*
- vendor/**/*
- node_modules/**/*
- .env-*
- .git*
- .rspec
- .slugignore
- LICENSE
- Gemfile*
- Procfile
- README.md
- Rakefile
- config.ru
- babel.config.js
