engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - "app/**/*"
  - "**.rb"
exclude_patterns:
- "**/*.yml"
- "**/*.js"
- "**/*.json"
exclude_paths:
- app/assets/**/*
- app/locales/**/*
- app/views/**/*
- bin/**/*
- config/**/*
- db/**/*
- doc/**/*
- lib/**/*
- public/**/*
- vendor/**/*
- .env-*
- .gitattributes
- .gitignore
- .rspec
- .slugignore
- LICENSE
- Gemfile
- Gemfile.lock
- Procfile
- README.md
- Rakefile
- config.ru
