version: '3.7'

services:
  mongo:
    image: sounerd/alpine-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.0.12-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mongo-data:

