version: '3.7'

services:
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:4.0.10-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mongo-data:

