I18n.locale = "pt-BR"
Activity.create(:type => "talk", :description => "Palestra", :order => 1)
Activity.create(:type => "interval", :description => "A definir", :order => 2)
Activity.create(:type => "interval", :description => "Credenciamento", :order => 3)
Activity.create(:type => "interval", :description => "Abertura", :order => 4)
Activity.create(:type => "interval", :description => "Intervalo", :order => 5)
Activity.create(:type => "interval", :description => "Lanche", :order => 6)
Activity.create(:type => "interval", :description => "Almoço", :order => 7)
Activity.create(:type => "interval", :description => "Fishbowl", :order => 8)
Activity.create(:type => "interval", :description => "Encerramento", :order => 9)